
/**************************************************************\
Edition (auto):
##  --/--/---- by generate_exception_header.py

File Name:
##  @file generated_exception_header.hpp

File Description:
##  Header auto generated by the python script at compilation
##  Generated from the files in 'cmake/config/exception/'
##  Used for exception code & message definition
\**************************************************************/

#ifndef GENERATED_EXCEPTION_HEADER_H
    #define GENERATED_EXCEPTION_HEADER_H

    //----------------------------------------------------------------//
    /* INCLUDE */

    #include <iterator>
    #include <cstddef>

namespace utils::exception { // namespace start
//----------------------------------------------------------------//
/* TYPEDEF */

/* Definition of the different exception code */
enum Code {
    Undefined = 0,
    MouseEvent,
    InvalidPtr,
    Dlopen,
    Dlsym,
    Dlclose,
    UnknowClassFactory,
    NoLoadedRender,
    NoLoadedGraphic,
    InvalidObject,
    InvalidAction,
    FailOpenWindow,
    CODE_SENTINEL // sentinel used for verification
};

/* Corresponding exception message for each code */
constexpr inline const char *Message[] = {
    /* Undefined */ "An undefined error has occured",
    /* MouseEvent */ "Error during the read of the mouse event",
    /* InvalidPtr */ "Invalid pointer used (null)",
    /* Dlopen */ "Failed to load a dynamic library",
    /* Dlsym */ "Failed to load a function from a dynamic library",
    /* Dlclose */ "Failed to release a loaded dynamic library",
    /* UnknowClassFactory */ "An unknow class name was given to the factory",
    /* NoLoadedRender */ "Wasn't able to load the render library",
    /* NoLoadedGraphic */ "Wasn't able to load the graphics library",
    /* InvalidObject */ "Invalid object used",
    /* InvalidAction */ "Can't execute the given action",
    /* FailOpenWindow */ "Fail during the creation of the window"
};

// Check at the compile time the correspondece between the message & code
static_assert(std::size(Message) == static_cast<std::size_t>(utils::exception::Code::CODE_SENTINEL), "The message array doesn't correspond to the available exception codes");

} // namespace end
#endif /* GENERATED_EXCEPTION_HEADER_H */
