"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""

 ██╗  ██╗ █████╗ ██████╗ ████████╗ █████╗ ███╗   ██╗██╗ █████╗ 
 ╚██╗██╔╝██╔══██╗██╔══██╗╚══██╔══╝██╔══██╗████╗  ██║██║██╔══██╗
  ╚███╔╝ ███████║██████╔╝   ██║   ███████║██╔██╗ ██║██║███████║
  ██╔██╗ ██╔══██║██╔══██╗   ██║   ██╔══██║██║╚██╗██║██║██╔══██║
 ██╔╝ ██╗██║  ██║██║  ██║   ██║   ██║  ██║██║ ╚████║██║██║  ██║
 ╚═╝  ╚═╝╚═╝  ╚═╝╚═╝  ╚═╝   ╚═╝   ╚═╝  ╚═╝╚═╝  ╚═══╝╚═╝╚═╝  ╚═╝

Edition:
##  04/03/2026 by Tsukini

File Name:
##  generate_exception_header.py

File Description:
##  Generate the exception header from the config file
"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""

##### Import #####
# Import that can't be in the try
from const import Return, Error, Value, File, Name
from sys import exit, executable
from subprocess import check_call

# Try to install dependencies
try:
    check_call([executable, "-m", "ensurepip", "--upgrade"])
    check_call([executable, "-m", "pip", "install", "-r", File.REQUIREMENTS])
except Exception as e:
    pass

# Import that can be checked
try:
    import re # Used for pattern matching
    import json # Used to get the json data
    from pathlib import Path # Used to create & edit files and to get the file name
except ImportError as e:
    print(f"Import Error: {e}")
    print(f"Auto generated header '{File.GENERATED_EXCEPTION_HEADER}': FAIL")
    exit(Error.FATAL)

##### Program #####
# Check if the program is call and not imported
if __name__ != "__main__":
    print("The script of the cmake can only be executed and not imported!")
    print(f"Auto generated header '{File.GENERATED_EXCEPTION_HEADER}': FAIL")
    exit(Error.FATAL)

# Recuperation of the data
data = {} # {code: [message, info, restriction], ...}
for json_file in Path(File.CONFIG_EXCEPTION).glob("*.json"):
    with json_file.open("r", encoding="utf-8") as f:
        json_content = json.load(f)
        for error in json_content.get("errors", []):
            if json_content.__contains__(error["code"]):
                print("Duplicated error code encoutered in data extraction")
                print(f"Auto generated header '{File.GENERATED_EXCEPTION_HEADER}': FAIL")
                exit(Error.KO)
            data[error["code"]] = [error["message"], error["info"] if error.__contains__("info") else "[None]", error["restrictions"] if error.__contains__("restrictions") else []]

# fichier à parser
cpp_file = ""

# Patern to find enum value
enum_pattern = re.compile(r'^\s*(\w+)\s*=\s*(0b[01]+)\s*,?')

# Extract the enum values
with open(File.EXCEPTION_DEFINE_HEADER, "r", encoding="utf-8") as f:
    inside_enum = False
    for line in f:
        # Detect the start of the enum
        if "enum Type" in line:
            inside_enum = True
            continue
        # Detect the end of the enum
        if inside_enum and "};" in line:
            inside_enum = False
            continue
        # Inside the enum, extartc values
        if inside_enum:
            match = enum_pattern.match(line)
            if match:
                name, value = match.groups()
                Value.EXCEPTION_TYPE[name] = int(value, 2)

# Format the data
code_str = ""
message_str = ""
info_str = ""
restriction_str = ""
data_list = list(data.items())
for i, (code, [message, info, restriction]) in enumerate(data_list):
    # code
    code_str += f"    {code},"
    # message
    escaped_message = message.replace('"', r'\"')
    message_str += f'    /* {code} */ "{escaped_message}",'
    # info
    escaped_info = info.replace('"', r'\"')
    info_str += f'    /* {code} */ {"nullptr" if escaped_info == "[None]" else ("\"" + escaped_info + "\"")},'
    # restriction
    value = 0
    types = ""
    for j in range(len(restriction)):
        t = restriction[j]
        value |= Value.EXCEPTION_TYPE.get(t, 0)
        if Value.EXCEPTION_TYPE.get(t, 0) != 0: types += t + (", " if j != len(restriction) - 1 else "")
    restriction_str += f"    /* {code} */ {value:#06b}, // allow: {'All' if types == '' else types}"
    # End of line
    if i != len(data_list) - 1:
        code_str += "\n"
        info_str += "\n"
        message_str += "\n"
        restriction_str += "\n"

# Build the restriction comment
restriction_lines = [
    "// 0b0000 = no restriction\t(allow all)",
]
for name in Value.EXCEPTION_TYPE:
    restriction_lines.append(f"// {Value.EXCEPTION_TYPE[name]:#06b} = {name}\t\t\t(allow {name})")
restriction_str_comment = "\n".join(restriction_lines)

# Create the file
header = Path(File.GENERATED_EXCEPTION_HEADER)

# Build of the content
content = f"""
/**************************************************************\\
Edition (auto):
##  --/--/---- by {Path(__file__).name}

File Name:
##  @file {header.name}

File Description:
##  Header auto generated by the python script at compilation
##  Generated from the files in '{File.CONFIG_EXCEPTION}'
##  Used for exception code & message definition
\\**************************************************************/

#ifndef {Path(File.GENERATED_EXCEPTION_HEADER).stem.upper()}_H
    #define {Path(File.GENERATED_EXCEPTION_HEADER).stem.upper()}_H

    //----------------------------------------------------------------//
    /* INCLUDE */

    #include <iterator> // std::size
    #include <cstddef>  // std::size_t
    #include <cstdint>  // std::uint8_t

namespace utils::exception {{ // namespace start
//----------------------------------------------------------------//
/* TYPEDEF */

/* Definition of the different exception code */
enum class Code: std::size_t {{
    Undefined = 0,
{code_str}
    CODE_SENTINEL // sentinel used for verification
}};

/* Corresponding exception message for each code */
constexpr inline const char *Message[] = {{
    /* Undefined */ "An undefined error has occured",
{message_str}
}};

/* Potential default info: nullptr same as "[None]" */
constexpr inline const char *Info[] = {{
    /* Undefined */ nullptr,
{info_str}
}};

/* Potential restriction on exception code */
{restriction_str_comment}
constexpr inline const std::uint8_t Restriction[] = {{
    /* Undefined */ 0b0000, // allow: All
{restriction_str}
}};

// Check at the compile time the correspondece between the message & code
static_assert(std::size(Message) == static_cast<std::size_t>(utils::exception::Code::CODE_SENTINEL), "The message array doesn't correspond to the available exception codes");
static_assert(std::size(Info) == static_cast<std::size_t>(utils::exception::Code::CODE_SENTINEL), "The info array doesn't correspond to the available exception codes");
static_assert(std::size(Restriction) == static_cast<std::size_t>(utils::exception::Code::CODE_SENTINEL), "The restriction array doesn't correspond to the available exception codes");

}} // namespace end
#endif /* {Path(File.GENERATED_EXCEPTION_HEADER).stem.upper()}_H */
"""

# Write the file content
header.write_text(content)

# Success
print(f"Auto generated header '{File.GENERATED_EXCEPTION_HEADER}': SUCCESS")
exit(Return.OK)
