"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""

 ██╗  ██╗ █████╗ ██████╗ ████████╗ █████╗ ███╗   ██╗██╗ █████╗ 
 ╚██╗██╔╝██╔══██╗██╔══██╗╚══██╔══╝██╔══██╗████╗  ██║██║██╔══██╗
  ╚███╔╝ ███████║██████╔╝   ██║   ███████║██╔██╗ ██║██║███████║
  ██╔██╗ ██╔══██║██╔══██╗   ██║   ██╔══██║██║╚██╗██║██║██╔══██║
 ██╔╝ ██╗██║  ██║██║  ██║   ██║   ██║  ██║██║ ╚████║██║██║  ██║
 ╚═╝  ╚═╝╚═╝  ╚═╝╚═╝  ╚═╝   ╚═╝   ╚═╝  ╚═╝╚═╝  ╚═══╝╚═╝╚═╝  ╚═╝

Edition:
##  04/03/2026 by Tsukini

File Name:
##  generate_exception_header.py

File Description:
##  Generate the exception header from the config file
"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""

##### Import #####
# Import that can't be in the try
from const import Return, Error, File, Name
from sys import exit, executable
from subprocess import check_call

# Try to install dependencies
try:
    check_call([executable, "-m", "ensurepip", "--upgrade"])
    check_call([executable, "-m", "pip", "install", "-r", File.REQUIREMENTS])
except Exception as e:
    pass

# Import that can be checked
try:
    import json # Used to get the json data
    from pathlib import Path # Used to create & edit files and to get the file name
except ImportError as e:
    print(f"Import Error: {e}")
    print(f"Auto generated header '{File.GENERATED_EXCEPTION_HEADER}': FAIL")
    exit(Error.FATAL)

##### Program #####
# Check if the program is call and not imported
if __name__ != "__main__":
    print("The script of the cmake can only be executed and not imported!")
    print(f"Auto generated header '{File.GENERATED_EXCEPTION_HEADER}': FAIL")
    exit(Error.FATAL)

# Recuperation of the data
data = {}
for json_file in Path(File.CONFIG_EXCEPTION).glob("*.json"):
    with json_file.open("r", encoding="utf-8") as f:
        json_content = json.load(f)
        for error in json_content.get("errors", []):
            if json_content.__contains__(error["code"]):
                print("Duplicated error code encoutered in data extraction")
                print(f"Auto generated header '{File.GENERATED_EXCEPTION_HEADER}': FAIL")
                exit(Error.KO)
            data[error["code"]] = error["message"]

# Format the data
code_str = ""
message_str = ""
data_list = list(data.items())
for i, (code, message) in enumerate(data_list):
    # code
    code_str += f"    {code},"
    if i != len(data_list) - 1: code_str += "\n"
    # message
    escaped = message.replace('"', r'\"')
    message_str += f'    /* {code} */ "{escaped}"'
    if i != len(data_list) - 1: message_str += ",\n"

# Create the file
header = Path(File.GENERATED_EXCEPTION_HEADER)

# Build of the content
content = f"""
/**************************************************************\\
Edition (auto):
##  --/--/---- by {Path(__file__).name}

File Name:
##  @file {header.name}

File Description:
##  Header auto generated by the python script at compilation
##  Generated from the files in '{File.CONFIG_EXCEPTION}'
##  Used for exception code & message definition
\\**************************************************************/

#ifndef {Path(File.GENERATED_EXCEPTION_HEADER).stem.upper()}_H
    #define {Path(File.GENERATED_EXCEPTION_HEADER).stem.upper()}_H

    //----------------------------------------------------------------//
    /* INCLUDE */

    #include <iterator>
    #include <cstddef>

namespace utils::exception {{ // namespace start
//----------------------------------------------------------------//
/* TYPEDEF */

/* Definition of the different exception code */
enum Code {{
    Undefined = 0,
{code_str}
    CODE_SENTINEL // sentinel used for verification
}};

/* Corresponding exception message for each code */
constexpr inline const char *Message[] = {{
    /* Undefined */ "An undefined error has occured",
{message_str}
}};

// Check at the compile time the correspondece between the message & code
static_assert(std::size(Message) == static_cast<std::size_t>(utils::exception::Code::CODE_SENTINEL), "The message array doesn't correspond to the available exception codes");

}} // namespace end
#endif /* {Path(File.GENERATED_EXCEPTION_HEADER).stem.upper()}_H */
"""

# Write the file content
header.write_text(content)

# Success
print(f"Auto generated header '{File.GENERATED_EXCEPTION_HEADER}': SUCCESS")
exit(Return.OK)
